name: AI Code Review

on:
  push:
    branches-ignore:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Code Review
      id: review_step  # step의 ID를 설정하여 이후에 결과를 참조 가능
      run: |
        python .github/scripts/review_code.py > review_output.txt
        review=$(cat review_output.txt)
        echo "::set-output name=review::$review"

    - name: Post review as a comment  # GitHub PR 코멘트 작성
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${{ steps.review_step.outputs.review }}\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments

