name: AI Code Review

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Code Review
      id: review_step
      run: |
        git fetch origin

        if git merge-base --is-ancestor origin/main HEAD; then
          git diff --name-only origin/main...HEAD > changed_files.txt
        else
          echo "No common ancestor, treating as first commit" > changed_files.txt
          git ls-files >> changed_files.txt
        fi

        python .github/scripts/review_code.py > review_output.txt || echo "Python script failed"
        
        # 리뷰 내용을 가져와서 "를 이스케이프 처리 후 환경 변수로 저장
        review=$(cat review_output.txt | sed 's/"/\\"/g')
        echo "review=$review" >> $GITHUB_ENV

    - name: Post review as a comment
      if: github.event_name == 'pull_request'
      run: |
        response=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${{ env.review }}\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
        echo "Response: $response"

