name: AI Code Review

on:
  push:
    branches-ignore:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Code Review
        id: review_step
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API 키 전달
        run: |
          # 현재 브랜치명 가져오기
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          
          # 원격 저장소에서 브랜치 정보 업데이트
          git fetch origin
          
          # 원격 브랜치와 로컬 브랜치의 차이점 확인
          git diff --name-only origin/$branch_name..HEAD > changed_files.txt
          
          # 변경된 파일이 있을 때만 Python 스크립트 실행
          if [ -s changed_files.txt ]; then
            python .github/scripts/review_code.py > review_output.txt || echo "Python script failed"
          else
            echo "No changes detected in this push" > review_output.txt
          fi

      - name: Post review as a commit comment
        run: |
          commit_sha=$(git rev-parse HEAD)
          review=$(cat review_output.txt | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$review\"}" \
            https://api.github.com/repos/${{ github.repository }}/commits/${commit_sha}/comments)
          echo "Response: $response"
