name: AI Code Review

# pull_request 이벤트에서만 워크플로우를 실행
jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Code Review
      id: review_step
      run: |
        python .github/scripts/review_code.py > review_output.txt || echo "Python script failed"
        review=$(cat review_output.txt || echo "No output generated")  # 파일이 없으면 에러 출력
        echo "review=$review" >> $GITHUB_ENV  # 환경 변수에 저장

    - name: Check review_output.txt existence
      run: |
        if [ -f "review_output.txt" ]; then
          echo "review_output.txt exists."
        else
          echo "review_output.txt does not exist."
        fi

    - name: Post review as a comment
      if: github.event_name == 'pull_request'
      run: |
        response=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${{ env.review }}\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
        echo "Response: $response"

